services:
  - type: web
    name: community-feed-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt && python backend/manage.py collectstatic --no-input && python backend/manage.py migrate
    startCommand: gunicorn --bind 0.0.0.0:$PORT --pythonpath backend community_feed.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: community-feed-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true

databases:
  - name: community-feed-db
    plan: free
